title: Rhythm Cons Wiki
description: Public wiki to store information about DIY and commercially available rhythm game controllers. 
theme: just-the-docs

url: https://rhythmconswiki.github.io

aux_links:
  "Contribute!": https://github.com/rhythmconswiki/rhythmconswiki.github.io
