title: Rhythm Cons Wiki
description: Public wiki to store information about DIY and commercially available rhythm game controllers. 
theme: just-the-docs

url: https://rhythmconswiki.github.io

aux_links:
  "Contribute!": https://github.com/rhythmconswiki/rhythmconswiki.github.io

permalink: pretty

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from